import type { TotoOfficialRoundLibraryMatch } from "@/lib/types";

export const featuredWorldTotoSourceUrl =
  "https://sp.toto-dream.com/dcs/subos/screen/si01/ssin025/PGSSIN02501ForwardSalesTermtotoSP.form?holdCntId=1634";

export const featuredWorldTotoVoteUrl =
  "https://sp.toto-dream.com/dcs/subos/screen/si01/ssin025/PGSSIN02501ForwardVotetotoSP.form?holdCntId=1634&commodityId=01&gameAssortment=A&fromId=SSIN026";

export const featuredWorldTotoTitle = "第1634回 toto W杯本番";
export const featuredWorldTotoSnapshotLabel = "2026-06-07 08:48-08:56時点";

export const featuredWorldTotoMatches: TotoOfficialRoundLibraryMatch[] = [
  {
    actualResult: null,
    awayTeam: "スイス",
    fixtureMasterId: null,
    homeTeam: "カタール",
    kickoffTime: "2026-06-14T04:00:00+09:00",
    matchStatus: "scheduled",
    officialMatchNo: 1,
    officialVote0: 0.1223,
    officialVote1: 0.0792,
    officialVote2: 0.7985,
    sourceText: null,
    stage: "第1634回 toto",
    venue: null,
  },
  {
    actualResult: null,
    awayTeam: "モロッコ",
    fixtureMasterId: null,
    homeTeam: "ブラジル",
    kickoffTime: "2026-06-14T07:00:00+09:00",
    matchStatus: "scheduled",
    officialMatchNo: 2,
    officialVote0: 0.1962,
    officialVote1: 0.6613,
    officialVote2: 0.1425,
    sourceText: null,
    stage: "第1634回 toto",
    venue: null,
  },
  {
    actualResult: null,
    awayTeam: "キュラソー",
    fixtureMasterId: null,
    homeTeam: "ドイツ",
    kickoffTime: "2026-06-15T02:00:00+09:00",
    matchStatus: "scheduled",
    officialMatchNo: 3,
    officialVote0: 0.0531,
    officialVote1: 0.9041,
    officialVote2: 0.0428,
    sourceText: null,
    stage: "第1634回 toto",
    venue: null,
  },
  {
    actualResult: null,
    awayTeam: "日本",
    fixtureMasterId: null,
    homeTeam: "オランダ",
    kickoffTime: "2026-06-15T05:00:00+09:00",
    matchStatus: "scheduled",
    officialMatchNo: 4,
    officialVote0: 0.3066,
    officialVote1: 0.369,
    officialVote2: 0.3244,
    sourceText: null,
    stage: "第1634回 toto",
    venue: null,
  },
  {
    actualResult: null,
    awayTeam: "エジプト",
    fixtureMasterId: null,
    homeTeam: "ベルギー",
    kickoffTime: "2026-06-16T04:00:00+09:00",
    matchStatus: "scheduled",
    officialMatchNo: 5,
    officialVote0: 0.1218,
    officialVote1: 0.8024,
    officialVote2: 0.0758,
    sourceText: null,
    stage: "第1634回 toto",
    venue: null,
  },
  {
    actualResult: null,
    awayTeam: "ボスニア",
    fixtureMasterId: null,
    homeTeam: "カナダ",
    kickoffTime: "2026-06-13T04:00:00+09:00",
    matchStatus: "scheduled",
    officialMatchNo: 6,
    officialVote0: 0.2645,
    officialVote1: 0.5207,
    officialVote2: 0.2148,
    sourceText: null,
    stage: "第1634回 toto",
    venue: null,
  },
  {
    actualResult: null,
    awayTeam: "エクアドル",
    fixtureMasterId: null,
    homeTeam: "コートジボワール",
    kickoffTime: "2026-06-15T08:00:00+09:00",
    matchStatus: "scheduled",
    officialMatchNo: 7,
    officialVote0: 0.2902,
    officialVote1: 0.2725,
    officialVote2: 0.4373,
    sourceText: null,
    stage: "第1634回 toto",
    venue: null,
  },
  {
    actualResult: null,
    awayTeam: "カーボベルデ",
    fixtureMasterId: null,
    homeTeam: "スペイン",
    kickoffTime: "2026-06-16T01:00:00+09:00",
    matchStatus: "scheduled",
    officialMatchNo: 8,
    officialVote0: 0.0525,
    officialVote1: 0.9029,
    officialVote2: 0.0446,
    sourceText: null,
    stage: "第1634回 toto",
    venue: null,
  },
  {
    actualResult: null,
    awayTeam: "ウルグアイ",
    fixtureMasterId: null,
    homeTeam: "サウジアラビア",
    kickoffTime: "2026-06-16T07:00:00+09:00",
    matchStatus: "scheduled",
    officialMatchNo: 9,
    officialVote0: 0.1232,
    officialVote1: 0.0951,
    officialVote2: 0.7817,
    sourceText: null,
    stage: "第1634回 toto",
    venue: null,
  },
  {
    actualResult: null,
    awayTeam: "チュニジア",
    fixtureMasterId: null,
    homeTeam: "スウェーデン",
    kickoffTime: "2026-06-15T11:00:00+09:00",
    matchStatus: "scheduled",
    officialMatchNo: 10,
    officialVote0: 0.2852,
    officialVote1: 0.527,
    officialVote2: 0.1878,
    sourceText: null,
    stage: "第1634回 toto",
    venue: null,
  },
  {
    actualResult: null,
    awayTeam: "スコットランド",
    fixtureMasterId: null,
    homeTeam: "ハイチ",
    kickoffTime: "2026-06-14T10:00:00+09:00",
    matchStatus: "scheduled",
    officialMatchNo: 11,
    officialVote0: 0.0991,
    officialVote1: 0.0635,
    officialVote2: 0.8374,
    sourceText: null,
    stage: "第1634回 toto",
    venue: null,
  },
  {
    actualResult: null,
    awayTeam: "トルコ",
    fixtureMasterId: null,
    homeTeam: "オーストラリア",
    kickoffTime: "2026-06-14T13:00:00+09:00",
    matchStatus: "scheduled",
    officialMatchNo: 12,
    officialVote0: 0.2788,
    officialVote1: 0.2264,
    officialVote2: 0.4948,
    sourceText: null,
    stage: "第1634回 toto",
    venue: null,
  },
  {
    actualResult: null,
    awayTeam: "パラグアイ",
    fixtureMasterId: null,
    homeTeam: "アメリカ",
    kickoffTime: "2026-06-13T10:00:00+09:00",
    matchStatus: "scheduled",
    officialMatchNo: 13,
    officialVote0: 0.2174,
    officialVote1: 0.591,
    officialVote2: 0.1916,
    sourceText: null,
    stage: "第1634回 toto",
    venue: null,
  },
];

export function buildFeaturedWorldTotoSourceText() {
  return [
    `source,${featuredWorldTotoSourceUrl}`,
    `vote_source,${featuredWorldTotoVoteUrl}`,
    `snapshot,${featuredWorldTotoSnapshotLabel}`,
    "official_match_no,home_team,away_team,kickoff_time,official_vote_1,official_vote_0,official_vote_2",
    ...featuredWorldTotoMatches.map((match) =>
      [
        match.officialMatchNo,
        match.homeTeam,
        match.awayTeam,
        match.kickoffTime ?? "",
        match.officialVote1 ?? "",
        match.officialVote0 ?? "",
        match.officialVote2 ?? "",
      ].join(","),
    ),
  ].join("\n");
}

export function buildFeaturedWorldTotoImportPayload() {
  return {
    carryoverYen: 0,
    firstPrizeShare: 0.7,
    notes:
      "Hazi予想をすぐ入れるための第1634回toto公式スナップショットです。購入や精算は扱いません。",
    officialRoundName: "第1634回 toto",
    officialRoundNumber: 1634,
    payoutCapYen: null,
    productType: "toto13" as const,
    requiredMatchCount: 13,
    resultStatus: "selling" as const,
    returnRate: 0.5,
    rows: featuredWorldTotoMatches,
    salesEndAt: "2026-06-12T19:00:00+09:00",
    salesStartAt: "2026-06-06T08:00:00+09:00",
    sourceNote: `toto公式スマホ 第1634回 / 投票状況 ${featuredWorldTotoSnapshotLabel}`,
    sourceText: buildFeaturedWorldTotoSourceText(),
    sourceUrl: featuredWorldTotoSourceUrl,
    stakeYen: 100,
    status: "analyzing" as const,
    title: featuredWorldTotoTitle,
    totalSalesYen: 13958700,
  };
}
